name: bytebank_app
description: "ByteBank - Aplicativo de simulação bancária (FIAP Fase 3 Tech Challenge)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_app_check: ^0.3.2

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^14.6.1

  # UI & Charts
  fl_chart: ^0.70.2
  intl: ^0.20.2
  animations: ^2.0.11

  # Image Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Utils
  uuid: ^4.5.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5

  # Functional types
  fpdart: ^1.1.0

  # Reactive operators
  rxdart: ^0.28.0

  # Security
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  fake_cloud_firestore: ^3.0.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#4A914F"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
